### ISSUE TITLE
fill XXX in docstrings for exposure_time_calculator.py

### ISSUE THREAD

**Issue by emilleishida** [COINtoolbox/RESSPECT#12]
Things missing docstring:
num_atm_eff
prim_refl_filt
nread

**Comment by gongsale** [comment]
num_atm_eff: Atmospheric transmission at each center wavelength of the instrument filters (ugrizY). Default: [0.7,0.8,0.9,0.9,0.9,0.95]

prim_refl_filt: Reflectivity of the primary mirror at each center wavelength of the instrument filters (ugrizY). Default: [0.89,0.89,0.88,0.87,0.88,0.9]

nread: Number of times CCD is readout, i.e. for higher readout rates, this increases the noise. Default: 1

**Comment by emilleishida** [comment]
implemented after a long while!
