### ISSUE TITLE
testing.py in the main folder

### ISSUE THREAD

**Issue by emilleishida** [COINtoolbox/RESSPECT#40]
do we need this  `testing.py` file inside the main folder or should it be moved to the `tests/` directory?

**Comment by b1quint** [comment]
The `testing.py` module holds helper functions that are used for tests. Its location does not really matter as long as we update the `import` statements in the `test_*` files. 

In my opinion, this module should be either left out of the `test/` folder, or we should move its contents to `tests/conftest.py` and make it a fixture. This is a design choice.

**Comment by emilleishida** [comment]
ok, so since this is your design, I will close it considering it your choice :)
