### ISSUE TITLE
add documentation to cosmo_metric_utils.py module - cosmo_metric branch

### ISSUE THREAD

**Issue by emilleishida** [COINtoolbox/RESSPECT#7]
There are place holders for documentation in each function.

**Comment by kponder** [comment]
I updated the documentation. Let me know if something isn't clear or needs to be redone. 

Also, we can probably remove the `full_check` function.

**Comment by emilleishida** [comment]
Thanks I reviewed this and I think this is ok. 
Can you please just check if the comments I made about the dimension of the input data in function `compare_two_fishers is correct`?

I think at this point we can remove the `full_check function`.

**Comment by kponder** [comment]
I think the rows and columns are mixed. There should be 3 columns and N rows. I'll update and push.

**Comment by kponder** [comment]
Pushed.

**Comment by emilleishida** [comment]
thanks @kponder , I have just one more question. 
in the `compare_two_fisher` function,  it reads

`sig_fr1, cov1 = fisher_results(data1[0], data1[2])`
`sig_fr2, cov2 = fisher_results(data2[0], data2[2])`

and the input to the `fisher_results` function should be a list, so in this sense should we have:

`sig_fr1, cov1 = fisher_results(data1[:,0], data1[:,2])`
`sig_fr2, cov2 = fisher_results(data2[:,0], data2[:,2])`

instead? this would make the dimensionalities match what is described in the documentation.. or am I missing something?

**Comment by kponder** [comment]
I changed the documentation to match what was done. I don't think it makes sense to have the data as columns instead of rows.
