### ISSUE TITLE
option for get_distances

### ISSUE THREAD

**Issue by emilleishida** [COINtoolbox/RESSPECT#9]
Add the option to input the ids as a list. Current function only allows input via file.

**Comment by mi-dai** [comment]
It will be written to a list anyway, because it's hard for snana input to take a long list instead of a file. so either I can add a list option but write the file in get_distances module, or you just output a file in the top level pipeline. let me know what you prefer.

**Comment by emilleishida** [comment]
thanks @mi-dai , 
I did not know that was a requirement from SNANA.. no problem.
I will close this issue for now and we can continue working with the file. 
if necessary we can come back to this in the future.
